"""Twilio WhatsApp client for the Donor Engagement Agent.

Sends personalized engagement messages (generated by Bedrock) over WhatsApp.
In mock mode messages are appended to `outbox/whatsapp_log.jsonl` so the demo
runs offline.

Reply parsing (for inbound webhook):
  YES / HA / HAN / AYIO / HO  → CONFIRMED
  NO / NAHIN / ILLA / NAHI    → DECLINED
  MAYBE / SHAYAD              → MAYBE
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.config import settings

logger = logging.getLogger(__name__)

OUTBOX_DIR = Path(__file__).resolve().parent.parent.parent / "outbox"
WHATSAPP_LOG = OUTBOX_DIR / "whatsapp_log.jsonl"


@dataclass
class WhatsAppResult:
    to_phone: str
    body: str
    message_id: str
    status: str  # 'queued' | 'preview' | 'failed' | 'delivered'
    error: Optional[str] = None
    intended_phone: Optional[str] = None  # donor phone before override
    redirected: bool = False


def _ensure_outbox() -> Path:
    OUTBOX_DIR.mkdir(parents=True, exist_ok=True)
    return OUTBOX_DIR


def _normalize_to(phone: str) -> str:
    p = phone.strip().replace(" ", "")
    if not p:
        return p
    if not p.startswith("+"):
        # Default to India if a 10-digit local number was given
        digits = re.sub(r"\D", "", p)
        if len(digits) == 10:
            p = "+91" + digits
        elif len(digits) == 11 and digits.startswith("0"):
            p = "+91" + digits[1:]
        elif len(digits) > 10:
            p = "+" + digits
    return p


def _normalize_from() -> str:
    raw = (settings.twilio_whatsapp_from or "").strip()
    if not raw:
        return ""
    if raw.startswith("whatsapp:"):
        return raw
    if not raw.startswith("+"):
        raw = "+" + re.sub(r"\D", "", raw)
    return f"whatsapp:{raw}"


def _mock_send(to_phone: str, body: str, kind: str) -> WhatsAppResult:
    _ensure_outbox()
    entry = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "channel": "whatsapp",
        "kind": kind,
        "to": to_phone,
        "body": body,
        "from": settings.twilio_whatsapp_from or "+14155238886 (sandbox)",
    }
    with WHATSAPP_LOG.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry) + "\n")
    msg_id = f"wa-mock-{datetime.utcnow().timestamp():.0f}"
    logger.info("WhatsApp [mock] → %s (%d chars)", to_phone, len(body))
    return WhatsAppResult(to_phone=to_phone, body=body, message_id=msg_id, status="queued")


def send_whatsapp(phone: str, body: str, *, kind: str = "engagement") -> WhatsAppResult:
    """Send a WhatsApp message via Twilio. Logs to outbox if mocks enabled."""
    intended = _normalize_to(phone)
    to_phone = intended
    if not to_phone:
        return WhatsAppResult(to_phone=phone, body=body, message_id="", status="failed", error="empty_phone")

    redirected = False
    override = (settings.sms_override_phone or "").strip()
    if override:
        to_phone = _normalize_to(override)
        redirected = bool(to_phone and to_phone != intended)
        if redirected:
            logger.info("WhatsApp redirect %s → %s (SMS_OVERRIDE_PHONE)", intended, to_phone)

    if settings.twilio_mocks_enabled:
        result = _mock_send(to_phone, body, kind)
        result.intended_phone = intended
        result.redirected = redirected
        return result

    try:
        from twilio.rest import Client
    except ImportError as exc:
        logger.warning("twilio package missing — falling back to mock: %s", exc)
        return _mock_send(to_phone, body, kind)

    from_addr = _normalize_from()
    if not from_addr:
        logger.warning("TWILIO_WHATSAPP_FROM not set — falling back to mock")
        return _mock_send(to_phone, body, kind)

    try:
        client = Client(settings.twilio_account_sid, settings.twilio_auth_token)
        msg = client.messages.create(
            from_=from_addr,
            to=f"whatsapp:{to_phone}",
            body=body,
        )
        logger.info(
            "Twilio WhatsApp OK → %s (sid=%s, status=%s)",
            to_phone,
            msg.sid,
            msg.status,
        )
        # Mirror to outbox for auditing during demo
        _ensure_outbox()
        with WHATSAPP_LOG.open("a", encoding="utf-8") as fh:
            fh.write(
                json.dumps(
                    {
                        "timestamp": datetime.utcnow().isoformat() + "Z",
                        "channel": "whatsapp",
                        "kind": kind,
                        "to": to_phone,
                        "body": body,
                        "twilio_sid": msg.sid,
                        "status": msg.status,
                    }
                )
                + "\n"
            )
        return WhatsAppResult(
            to_phone=to_phone,
            body=body,
            message_id=msg.sid,
            status=msg.status or "queued",
            intended_phone=intended,
            redirected=redirected,
        )
    except Exception as exc:
        logger.exception("Twilio WhatsApp send failed → %s", to_phone)
        return WhatsAppResult(
            to_phone=to_phone,
            body=body,
            message_id="",
            status="failed",
            error=str(exc),
            intended_phone=intended,
            redirected=redirected,
        )


# ─── Inbound reply classification ──────────────────────────────────────


_YES_TOKENS = {"YES", "Y", "HA", "HAN", "HAAN", "AYIO", "AVUNU", "AAVUNU", "HO", "OK", "OKAY", "DONE"}
_NO_TOKENS = {"NO", "N", "NAHIN", "NAHI", "ILLA", "VADDU", "MATTE"}
_MAYBE_TOKENS = {"MAYBE", "SHAYAD", "BELKI", "PERHAPS"}
_STOP_TOKENS = {"STOP", "UNSUBSCRIBE", "QUIT", "CANCEL", "END"}


def classify_response(message: Optional[str]) -> Optional[str]:
    if not message:
        return None
    token = message.strip().upper().split()[0] if message.strip() else ""
    token = re.sub(r"[^A-Z]", "", token)
    if token in _STOP_TOKENS:
        return "STOP"
    if token in _YES_TOKENS:
        return "CONFIRMED"
    if token in _NO_TOKENS:
        return "DECLINED"
    if token in _MAYBE_TOKENS:
        return "MAYBE"
    return None


def parse_twilio_webhook(form: dict) -> dict:
    """Twilio sends: From=whatsapp:+91xxx, Body=YES, ProfileName=…, MessageSid=…"""
    return {
        "from": (form.get("From", "") or "").replace("whatsapp:", "").strip(),
        "message": (form.get("Body", "") or "").strip(),
        "profile_name": form.get("ProfileName", "") or "",
        "message_sid": form.get("MessageSid", "") or "",
    }
